---
GenerationParams:
  MapScale: 1.0          # how much the sectors are spread out  
  # float [0..1] solar systems are more like a cookie than a ball. the lower the value, the flatter the system
  SolarSystemSqueezeMinMax: [0.005, 0.005] 
  # float [0..1] probability a warp connection will be one-way
  OneWayWarpProb: 0
  UniqueStarterPlanet: true
  
  #==== 1st Step of SolarSystem Generation: setting amount and playfield types  for System Content  ===

  PlanetCountProbs:
     - '0 : 0.1,   1 : 0.5,  2 : 0.3,  3 : 0.1'           # 1 - GasPlanets: defines the min-max amount of playfields. Each Amount can have an individual probability. Combinations of amounts with and without probabilies is possible. If no individual probability is set, the 'amount number' will get an average of the remaining probability. Example [0:0.1,3]  > 0 has probability 10%. 1,2 and 3 share the other 90% = 1 has 30%, 2 has 30%, 3 has 30%
     - '0 : 0.4,   1 : 0.5,  2 : 0.1'                     # 2 - Hot Planets
     - '0 : 0.5,   1 : 0.4,  2 : 0.1'                     # 3 - Dry planets
     - '0 : 0.4,   1 : 0.4,  2 : 0.2'                     # 4 - Temperate planets
     - '0 : 0.8,   1 : 0.2'                               # 5 - Alien planets
     - '0 : 0.6,   1 : 0.4'                               # 6 - Snow planets
     - '0 : 0.1,   1 : 0.6,  2 : 0.3'                     # 7 - Barren
  #Organizes the GasPlanets class lables and their [probability] to show up for any of the 'GasPlanets slots' drawn in the 1st Step
  PlanetLists:           # Lable name depicts, in a descriptive way, the class or global or visual approach of the playfields summarized under this lable; playfields are added in the *Types sections
    - 'Jupiter:0.45, Saturn: 0.35, Neptun:0.2'                                                # 1 GasPlanets
    - 'LavaLegacy:0.4'                                                                        # 2 Hot
    - 'AridLegacy:0.3, DesertLegacy:0.2, SyndicateOG:0.5'                                     # 3 Dry
    - 'OceanLegacy:0.2, GalorianOG:0.3, HomeworldPolaris:0.3, Temperate:0.2'                  # 4 Temperate
    - 'AlienLegacy:0.3'                                                                       # 5 Alien
    - 'SnowLegacy:0.6, TaloniaOG:0.4'                                                         # 6 Snow
    - 'BarrenLegacy:0.5'                                                                      # 7 Barren

  POICountProbs: '0 : 0.05,  1 : 0.1,  2 : 0.1,  3 : 0.2,  4 : 0.2,  5 : 0.2,  6 : 0.1,  7 : 0.05'
  POIs: 'SpaceEmptyPvP: 0.3, SpaceAsteroidFieldLegacy: 0.3, AsteroidField: 0.35, ArecthoriosPVP:0.05'  
  
  PlanetTypes:      # come up with general categories of planet (playfield) types for distance purposes
      - Name: Temperate
        Color: [0.04, 0.5, 0.1]
        Placement:
            - HabitableTemperate
        MoonProb: '0:0.5, 1:0.3, 2:0.1, 3:0.1'
        MoonType: [MoonBasic, MoonFaction]
        OrbitType: [DefaultOrbit]
        Climate: Temperate
        PlayfieldLevel: [2,6]
        Playfields:
            - Temperate

  # ======== Moon Types ================
  MoonTypes:
      - Name: DefaultMoon          # definition of default name 'DefaultMoon' is mandatory
        Color: [0,0,0]
        Distance: [6000, 12000]
        HasOrbit: false
        HasTerrain: true
        PlayfieldLevel: [1,10]
        Playfields:
            - Moon 

  # ======== POIs ================
  POITypes:
      - Name: SpaceEmpty
        Color: [0.49, 0.49, 0.49]
        Icon: SpaceEmpty
        Placement:
            - InnerSystem
            - HabitableHot
            - HabitableTemperate
            - HabitableCold
            - OuterSystem
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [2,10]
        Playfields:
            - SpaceEmptyPvP
            
  # ======== Stations ================            
  StationTypes:
      - Name: SpaceTradingStation
        Color: [0.7, 0.5, 0.0]
        Icon: Station
        Distance: [200, 300]
        Placement: 
          - InnerSystem
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [2,10]
        Playfields:
            - SpaceTradingStation
            
  # ======== OrbitTypes ================
  OrbitTypes:
      - Name: DefaultOrbit     # definition of default name 'DefaultOrbit' is mandatory
        Color: [0.3, 0.3, 0.3]
        Distance: [270, 870]
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [2,10]
        Playfields:
            - SpaceOrbit, 0.1
            - OrbitEasyNew, 0.3
            - OrbitMediumNew, 0.3
            - OrbitHardNew, 0.2
            - OrbitMulti, 0.1

# -------------------------------------------------------------------------- Sun Playfield
  WarpTargetOrbitTypes:
      - Name: WarpTarget
        Color: [0.3, 0.3, 0.3]
        Distance: [270, 870]
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [1,4]
        Playfields:
            - SpaceWarpTarget
